### ISSUE TITLE
Good Neighborhood definition - research criteria in Moving to Opportunity

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#104]
Recent research on the Moving to Opportunity program shows the results of a long term longitudinal study looking at the effect on children of living in better neighborhoods. 

We want to know the specific data fields they used to decide their definition of a 'better neighborhood'. We will use this to inform what data to include about the neighborhoods. 
- [ ] Make a list of all the publicly data types used in the paper and where we can find them (e.g. income distribution from the American Community Survey)
- [ ] Track down where and how to obtain each of the data sets. If the data comes from Census and is available via the American Fact Finder, we need the specific table number - see my next note on how to download data from AFF, it is confusing. Not necessary to download all of them at this time - we'll want to double check the sources once they are all listed. 
- [ ] Record the thresholds used in the study for 'poor' and 'good' neighborhoods (or whatever other levels they include)

This NY Times article has a good summary of the results of the report (age dependent, but clearly positive to live in a better neighborhood): https://www.nytimes.com/2015/05/05/upshot/why-the-new-research-on-mobility-matters-an-economists-view.html?_r=0 

Original paper: http://scholar.harvard.edu/files/hendren/files/nbhds_paper.pdf

It looks like most of what we need will be in the table at the end of the document.

**Comment by NealHumphrey** [comment]
As I said it's not necessary to actually download the data from ACS or Census yet, but we do need to find the specific table to use. You can browse those via the American Fact Finder using the same process you would use to download the data. Steps are here:
https://github.com/codefordc/housing-insights/wiki/American-Community-Survey---Download-Instructions

**Comment by NealHumphrey** [comment]
@rmcarder I'm assigning this to you per the printouts you showed me last night. Can you cross check your highlighted fields against where to get the data sources and add them to the manifest.csv file as we talked about? You can leave the S3 path blank for now, but use the notes field to provide instructions or comments on them. You can make a pull request with the manifest updates, and next week I can get you set up with the rest of the new data ingestion process (i.e. making the metadata file and actually loading the data into the database).

**Comment by NealHumphrey** [comment]
Hey @rmcarder where does this stand? Can you add a list of tables to issue #152 so that they can pull the data from there?

**Comment by NealHumphrey** [comment]
Hey @rmcarder do you still have the printed list of tables you reviewed? Did this ever make it somewhere shareable?

**Comment by NealHumphrey** [comment]
Here is the Census webpage that has all of the field names and codes: 
http://api.census.gov/data/2015/acs5/variables.html

**Comment by MikeS-nth** [comment]
@NealHumphrey:  I've made some progress on this and wanted to give you a quick update on where things stand:

I've learned a couple relevant things about the variables in the Harvard study:
- It seems the values are not pulled directly from the census; rather, they are metrics/measures that are derived using the census as source data.  For example, Racial Segregation takes several census values and calculates a value for segregation based on the "Theil index" [https://en.wikipedia.org/wiki/Theil_index](https://en.wikipedia.org/wiki/Theil_index )
- The source data for these variables is pulled from the 2000 census, not the ACS.  
- Some of the variables can be pretty well matched to the ACS API fields; others might be trickier.

Based on my preliminary understanding of the project, it seems like implementing these variables into the site would require pulling the relevant field from the ACS API, and also transforming them to best match the Harvard study definitions.

Here are two outputs thus far:
- [CSV of all ACS API fields from the website](https://drive.google.com/open?id=0B1LdxHu1oI3dcnRpWWdHamw5UVE)  (it's 50+MB so didn't want to push it to GitHub)
- [Work in progress of mapping the Harvard study variables to ACS API fields and/or how we would need to calculate the equivalent variables using ACS data](https://docs.google.com/spreadsheets/d/19hYYxBwef1jJ4YzJp4behdmJmAQtYvkSyhrPAsicwLo/edit?usp=sharing)

I created a Python script to scrape the ACS fields and put them into a Sqlite db to make it more feasible to do keyword searches on census field name vs. ACS field name.  Wasn't sure if this was worth a pull request, since it's meant as an EDA/munging file, rather than a production file.

Will continue to work on this and complete the mapping as soon as I can.  I'll be out of pocket for the rest of today.

**Comment by NealHumphrey** [comment]
@MikeS-nth sounds like great progress - thanks for the update! 

We can also pull data from the Dicennial Census in addition to the American Community Survey - we started with ACS because it seemed to have more of the stuff we were interested in. We'll want to pull ours from the 2010 census, though, as it's the most recent. Here's documentation on the [Dicennial Census API](https://www.census.gov/data/developers/data-sets/decennial-census.html) and specifically the [variable list](http://api.census.gov/data/2010/sf1/variables.html) with similar column codes we'll need to make the API call. 

For next week's launch we could incorporate a couple calculated variables in addition to directly-available ones. We'd just want to do 2 or 3 easy to calculate ones for now - poverty rate for example - while we can defer the rest to potentially include in V2 that will launch in August. So, as you fill out that mapping keep in mind near-term vs. longer-term uses. 

Thanks for your work on this!

**Comment by MikeS-nth** [comment]
Hi @NealHumphrey: 

Sorry for the lag on this.  Picking a handful of easy-to-calculate fields for this rev makes total sense.  I've added a new tab to the google sheet with 6 that I think are viable candidates.  In the "Pseudocode" column, I've included the ACS API fields and the calculation logic (they are all simple ratios).

Please let me know if you think this will work.  Anything I can do to help with implementation?

[Here's the link to the google sheet.  Please see first tab ("For v1")](https://docs.google.com/spreadsheets/d/19hYYxBwef1jJ4YzJp4behdmJmAQtYvkSyhrPAsicwLo/edit?usp=sharing)

mike

**Comment by NealHumphrey** [comment]
@MikeS-nth not a problem - thanks for the update!

I think those 6 look like a great starting point. If you want to help with implementation that would be great. 

To implement, 1) we need to add the column names to our api download, which is pretty easy. In `/python/housinginsights/sources/census.py`, add the appropriate column names to the list of fields we want to get from the census API in the __init__ section. To test it, you can just run census.py directly from the command line and it should create a csv file in `/data/raw/apis/YYYYMMDD` with the current date stamp. I'll want this tomorrow so that I can integrate w/ other code, so if you're able to do this tonight great - and if not I can do it tomorrow. 

2) This can be wrapped up over the next couple days, but the most useful other thing is to add some basic documentation to a new file called `/docs/data/census.md`. It's basically transferring what you described in the spreadsheet into our actual documentation, into a website-ready format. Note @emkap01 had mentioned starting on this but I just checked in w/ him and he hasn't started yet, so it's all you - let me know if you're able to take a crack at it. 

To actually get the data from our database into the front end it is probably easier if I do it tomorrow, as it depends on the work being done by @ajhalani in #180, so I'll need to integrate the two. We'll get you digging into some Python code next week :)

Let me know if you do take a stab at part 1 tonight, otherwise I can add it. Thanks!

**Comment by MikeS-nth** [comment]
@NealHumphrey sounds good; I'll get cracking on #1 right now.  I'll also start in on #2 once #1 is done.

**Comment by ptatian** [comment]
@NealHumphrey @MikeS-nth Hi guys, just to give some context, there's probably limited value in the decennial census data at this point, since it's 7 years out of date. The most useful thing about the decennial data are that they are based on a **full count** of the population, so small area (tract) pop counts are reliable. In other words, if I wanted to know **how many more people** there are in a tract between 2000 and 2010, the decennial census gives pretty good estimate. In contrast, the ACS can't be used to estimate **changes in population counts**. But for more current conditions based on **percentages** (ex,, % persons who are African-American), ACS is the better source.  

I hope that's helpful. Let me know if you have questions.
