### ISSUE TITLE
POC: Use AWS Lambda to serve meta.json

### ISSUE THREAD

**Issue by prisalex** [codefordc/housing-insights#142]
Proof of concept to show that we can use Lambda as our API layer/server for UI team. 
- Initially serve up meta.json 
- Future APIs to retrieve entire tables via table_name

Known bugs with test API: 
1. FIXED - Following tables can't be queried because datetimes aren't serializing: building_permits, manifest, project

**Comment by NealHumphrey** [comment]
From Priscilla: 
So checking out lambda and there are some challenges for developing it. I think the two big ones are code mgmt and testing locally. 

Code management:
I’ve been playing around by editing in AWS GUI which is not the best approach for the real deal.  Essentially we have to create a workflow to zip up the code from git and deploy it to the server.

Local Testing:
Does not look easy to do. I'm going to investigate that a bit more but I think that could be problematic from a dev perspective if in order for an individual to update an endpoint they have to actually push it to the server

It is possible to create “test” instances that you can push up to first before deploying “for real”. I’m going to look at how hard it is to create the “deployment package” and upload it from the CLI to a test instance. But that doesn’t strike me as optimal either. 

The other option is that we look at a framework that will take some of the “pain” out of creating a server. Serverless Framework is one.  It has a lot of big folks backing it but one challenge is that it is in beta. 

More research notes to come.

**Comment by NealHumphrey** [comment]
@prisalex Looking into this more, here's some notes

Here are some additional options/notes for local testing:
- [Serverless](https://serverless.com/) looks pretty ready to use despite being in beta. Looks like it is set up to manage configuration and deployment, but doesn't do local testing. I saw [one guy say](http://stackoverflow.com/questions/34470297/testing-aws-lambdas-locally-behind-api-gateway-endpoints) they set up a staging environment for each developer, so 'local' testing occurs by each developer having their own sandbox environment. Since it's pay-per-command (instead of user) it should be OK for us to do this too if need be. 
- [Bespoken Tools](http://docs.bespoken.tools/en/latest/tutorials/tutorial_lambda_local/) has a package to run Lambdas locally. Looks straightforward but simplistic.
- [Docker Lambda](https://github.com/lambci/docker-lambda) has docker images set up to replicate the AWS Lambda environment. It's unclear how to use this to test local API endpoints, though. 

Other issues:
- Lambda only offers Python 2.7 (sad face). All our current code is in 3.5. If we go this route, we'd want to convert all our existing code back to 2.7, which kinda sucks. 

Other options:
- We could go ahead and go for a server. It's not too hard to create api frameworks using [Flask](https://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask) or [Django](http://www.django-rest-framework.org/). My impression is that Flask is a bit simpler, but a few more people know Django (Django would be the better choice for a complex website with users, logins, etc.). I've made a basic website in Flask so I'm slightly more comfortable with it, but learning Django's not a bad idea. We should estimate how big a 
- Here's [a full list](https://www.fullstackpython.com/api-creation.html) of Python API creation options.

**Comment by NealHumphrey** [comment]
In short, Lambda is looking a bit trickier than I first thought, but still worth investigating those options especially serverless.

**Comment by prisalex** [comment]
Ok, I have a test version of the API available.  Just do an HTTP GET like so and provide the tablename as a query param:

https://zjlpq5zz7e.execute-api.us-east-1.amazonaws.com/test/raw?tablename=acs_rent_upper

Some notes: 
- It returns a json version of the data that should correspond to the meta.json file.  
- I am currently limiting the output to 1000 rows because I suspect the performance is going to be abysmal for some or the larger tables and we will probably need to limit the queries.  The acs* tables are already 500K rows.   So trying to test performance myself with no limits first before opening up the API.
- The URI is not permanent; this is on my local AMZ account until I get feedback and clean & check in the code. 
- You can connect to the postgres DB to see which tables are there.  If a tablename param is missing or doesn't exist, you'll get a 400 http status code. 

UI devs, let me know if you have feedback!

**Comment by prisalex** [comment]
Also, let me know if you find any bugs.  Just found one with the building_permits table because I didn't handle dates yet... blerg.

**Comment by prisalex** [comment]
Fixed the issues with dates so all existing tables should be good to go :).  If you want to get the raw csv file, you can now get that by querying the _manifest_ table and then concatenating s3_folder+filepath.

**Comment by NealHumphrey** [comment]
Couple bug notes:
@prisalex it looks like decimal formats are not serializing also. On the project table, 'proj_lat' and proj_lon are two examples, but it looks like all of the decimal fields are returning null. 

On the dates, would it be better to return them as a JSON date format instead of a yyyy-mm-dd string? That can be converted to something prettier client-side, but then it doesn't have to be parsed to be calculated. @ostermanj and @ptgott what do you think?

FYI, currently we have the following data formats in our database. You can see this in the 'type' attribute of any field in meta.json.
- text
- decimal
- integer
- datestamp
- timestamp

**Comment by NealHumphrey** [comment]
Usability note: Obviously this is a proof of concept, but as we start converting it to the real thing we should also try to apply REST format to the API methods instead of params, e.g.:
`list all records: /api/<tablename>`
`individual building: /api/projects/<nlihc_id>`

We'll also want to think about this with respect to the unique ids for some tables. For example, currently acs_median_rent does not have a single unique id for a row - the combo of census tract and unique_data_id (i.e. year of the data) make the unique id. For those, we may want to assign a unique id column, and/or make our rest API do something like:
`/api/acs_median_rent/2015/<tract>` and
`/api/acs_median_rent/all/<tract>`

**Comment by NealHumphrey** [comment]
Also - yes, let's keep the API limited for now. For the ACS tables, those will very soon get smaller as part of #152, when not only will we end up with just DC census tracts we'll also get one big table with a column for every census field. But, we do have other DC-only data sets that will be quite large - e.g. building permits,  police department events, 311 calls, especially since we'll be keeping a record of them over time.

**Comment by ptgott** [comment]
@NealHumphrey I'm okay with either format! I'll let you know if I run into any issues with one format or another.

**Comment by NealHumphrey** [comment]
@ptgott I was thinking for example about the timeline viz, where dates are obviously used as numbers. In addition, it seems like it might be easier to go straight from the JSON timestamp to whatever display format we want (Oct. 26 vs 10-26 vs. October 26), which would be more flexible to changes. But then we can never use the datestamp directly (seconds since 1970 isn't exactly easily readable). For something like a data export function that we know we'll want, we'll need to convert that.

**Comment by ptgott** [comment]
@NealHumphrey 
Is the intention with most of the (geo)JSON generally to process the values on the server and use them directly within the JS? I'd be in favor of using that approach with dates as well for consistency. At the same time, since we are using them as numbers within a D3 chart, that approach might give us unneeded difficulties. @wassona since you worked on the timeline chart, what do you think?

**Comment by prisalex** [comment]
Fixed the issue with decimals; they should be outputting now.  Let me know thoughts on date & timestamp format...

**Comment by prisalex** [comment]
In terms of the API design, I moved the proposal doc to here so we can collaborate more easily and then use it as the single source of truth for what is supported in the future: https://docs.google.com/document/d/1HG50BwRCZ8TMTY1xljROJYr8YLY5UHbjNZ6UcUqQ_HQ/edit#heading=h.2976f22qym3i

**Comment by NealHumphrey** [comment]
@prisalex can you push your code at least to your fork of the repo? Doesn't matter if it is still messy, you can keep it in its own feature branch and keep updating it. I'd just like to be able to investigate where things stand as we compare this to a SQLAlchemy/Falcon option as discussed Thursday.

**Comment by prisalex** [comment]
Here it is: https://github.com/prisalex/housing-insights/tree/lambdaPoc

I haven't actually done any work since we spoke.  Sorry!

I think both the SQL Alchemy work and the Falcon option could be done independently of this branch though.  I will take a look at that CORS issue now.  Should be an easy fix, me thinks.

**Comment by NealHumphrey** [comment]
Closing this per the shift to the Flask approach. Sad to see good code not used :( We may end up still using Lambda for some jobs depending how our server plays out, TBD.
