### ISSUE TITLE
MVP Additions ahead on demo Monday 4/17

### ISSUE THREAD

**Issue by ostermanj** [codefordc/housing-insights#193]
Here are the priorities coming out of tonight's work session for improvements to the MVP ahead of @NealHumphrey 's demo on Monday. It's all very related to the larger issue #143 .

1. Add ability to display **two fields** on top of the main map view: building permit count and crime count. These will be provided by API call, which should be ready for use by Wednesday evening. The API should return JSON (one array of objects) per zone aggregation type. Subtasks could be divided this way:

- [x] build menu, top-left of map, similar to zone selector that offers the two options of Crime and Building permit
- [x] selecting an option calls relevant API endpoint and returns appropriate data (or we fetch data on load in anticipation)
- [x] the harder part: have mapBox fill the zones based on the data

2. Link the selection of 'Neighborhood' to the options in the dropdown for the pie charts. (I can do this—didn't realize it was actually Neighborhood cluster, which has a one-to-one mapping to the project.csv data.

3. Add legend to map to explain the color-coding of the dots.

4. Leave the pie charts (NH edit: aggregating client side) ~~connected to static projects.csv file~~ (NH edit: now pulling from API) for now, but add (probably not programmatically—just force them in) the human readable field names as labels

5. Animate the pie charts when subzones are selected from the dropdown. I think this would be easier if the donuts were really showing just one arc ("yes") on top of a 360* background, rather than two arcs.

6. Some cleaning up of the building view page. Like can the be styled more like the map on the map view page? ~~Get rid of unused accordion sections?~~ (NH edit: should keep them we can fill in w/ some placeholders)

Let me know if anything's unclear, and let's let others know if you're jumping on anything.

**Comment by NealHumphrey** [comment]
Hey @ostermanj and @ptgott, moving conversation to this ticket for now until we get the version for Monday deployed - we can do a sweep of issue #143 after Monday to pick up any lingering issues we haven't dealt with yet. 

- The API endpoints I described in #143 are live on the Flask API. 
    - Use the format `http://hiapidemo.us-east-1.elasticbeanstalk.com/api/raw/<tablename>` to get the raw data for any table from these currently available options: `['census_mapping', 'project', 'subsidy', 'acs_rent_lower', 'acs_rent_median', 'crime', 'acs_rent_upper', 'manifest', 'building_permits']`
    - Use the format `http://hiapidemo.us-east-1.elasticbeanstalk.com/api/<tablename>/all/<zonetype>` for the tables `building_permits, crime` and zones of `anc, ward, neighborhood_cluster`. `zipcode` is available for building_permits only since zipcode wasn't in the source data for crime and we'll need to add a geocoding function - won't be there for Monday. 

- @ptgott 's code is merged in to dev, which provides the API version of the projects table. I upped the raw limit to 1,000 so that we'd get all project records from this endpoint (but so we wouldn't crash anything with 50,000 crime records in one endpoint). 

- I can focus on 6) if you all can focus on the map view items. I will try to add relevant API endpoints so that those views can be live updated (for example an endpoint that servers up building_permits within X miles). I may need your help with the Javascript side of stuff - and may hack some things in that will need better treatment using the getAPIData() approach.

**Comment by ptgott** [comment]
I'll have a stab today at the third part of (1), 'have mapBox fill the zones based on the data'. I'll set the 'visibility' layout property to 'none' to anticipate making the menu.

**Comment by ptgott** [comment]
In PR #201, I've implemented a version of the third task under item one. I've changed 'getAPIData()' in housing-insights.js into a slightly different function, 'getInitialData()', to reflect two things about it: first, it fetches data from the project server in general, rather than just the API; and second, in its current form, the code is meant to grab all data sources we might need for a given view before that view loads (there's currently an issue with this; see below).

I've also added an 'addDataToPolygons' function in rich-map.js, which adds values from the aggregate datasets to the appropriate geojson polygon FeatureCollection. Currently the third argument is a callback that converts the naming conventions of the geojson file to those of the API data, but we might be able to do away with this if the zone names within all of the API data differ from the zone names within all of the geojson polygon files in a consistent way.

Another thing to note: currently I've produced filled polygon layers for crime and building permits with zoning layers for ward and neighborhood-cluster. I've assigned the aggregates for both crime and building_permits within a single Mapbox source for each of ward and neighborhood_cluster. We can split these into separate sources if you'd like.

**Some other outstanding things**
1. We could add a 'loading' animation as the data load.

2. We could give app.dataCollection a more hierarchical structure. Currently I represent hierarchy using underscores ('crime_ward', 'crime_neighborhood'...).

3. There doesn't seem to be a geoJSON polygon source for ANC in the javascript/tool/data folder. 

4. I define the color range for the filled polygon layers arbitrarily. It's probably a good idea to use D3's ability to define ranges dynamically.

5. There's an outstanding issue in which in some browsers (e.g. Chrome), the map loads before the data do and prevents the proper map styling from taking place. We could put the map declaration within the 'prepareMaps()' callback in rich-map.js and fix whatever repercussions emerge from that (h/t to Neal Williams).

**Comment by NealHumphrey** [comment]
@ptgott, a couple responses:
- for your addDataToPolygons method, we should (after this weekend) work to get all data sources to behave consistently in how they use zone names. We can make sure the geoJSON and the API have the exact same label for each zone so that no callback is necessary. 
- I'm guessing a heirarchical structure for the data will be useful, e.g. nesting 'neighborhood' and 'ward' under 'crime' so that when we have many more data sources we can refactor the 'add layer' code to act dynamically on toggle instead of adding a layer for all of them. We should flag this for a post-MVP refactor discussion. 

Thanks for this! I've made some good progress on 6) and will be doing my own PR later today.

**Comment by nealfwilliams** [comment]
When using Firefox on my internet connection (it isn't great), the app doesn't always successfully finish all its API calls within the 10 x 500 millisecond time limit specified in housing-insights.js.  We probably want to bump this limit up before the demo, otherwise a slow internet connection could make the app totally nonfunctional.  See issue #209
