### ISSUE TITLE
Add functionality to make_draft_json for adding new sources

### ISSUE THREAD

**Issue by speedyturkey** [codefordc/housing-insights#196]
Currently, the make_all_json function in the make_draft_json module outputs individual json files - one per source in the manifest. This is tricky because adding a new source to meta.json requires the ability to manually review/edit the data (so it can't be totally automated).

Some ideas for additional functionality:

- A function to stitch together a group of individual json files
- A function to append new, cleaned, individual json files to an existing 'master' meta.json.

I am still new to this code so apologies if I am overlooking existing capabilities or misunderstanding the workflow in any way.

**Comment by NealHumphrey** [comment]
@speedyturkey  I recommend proceeding with just part 2 - a function to append new individual json to an existing master meta.json. Since we have a master json one already, there's no need to stitch together just individual ones. The make_draft_json will still produce one json file per table, the user will then manually validate it, and then the user will run the stitch function. 

Keep it simple, but core functionality should be:
- check that the tablename does not already exist in the table; give user the option to cancel or overwrite the meta for that table if it already exists.
- properly nest the json from a new table into the master file

**Comment by terrysky18** [comment]
I looked into the codes in make_draft_json while I was attempting to write an unit test script.  I would like to have a go at this task.

**Comment by NealHumphrey** [comment]
Go for it! Add yourself as an assignee and change the 'ready' label to 'in progress' whenever you actually start work on it.

**Comment by terrysky18** [comment]
Finally finished development for this bug fix.  Here is the list of changes:

- Added 'checkTable' function to check whether the new table is in table_info.json

- Added 'appendJSON' function to append the new table to table_info.json

- Added 'duplicateTable' function to handle when the new table is a duplicate entry in table_info.json.  User has the option either overwrite the entry or cancel.

- Added a new command line argument 'single-add' to handle the new process

I would like to do a code review before submitting a pull request.  Unit test scripts are still needed.
