### ISSUE TITLE
Investigate DCHD TOPA Monthly Filings for Ingestion

### ISSUE THREAD

**Issue by xee5ch** [codefordc/housing-insights#254]
Per conversation with @jkwening and the rest of the Browse/Ingestion Team, there is a high demand for TOPA data.  According to the DC website, they have monthly updates going back to 2016 listed below.

https://dhcd.dc.gov/page/weekly-report-tenant-opportunity-purchase-act-topa-filings

Each month links to a subsequent page with attached PDF, which appears to be a PDF export for from Excel directly.  Not sure the reliability, feasibility, and viable options for data massage and ingestion.  Will investigate further as part of #237 push.

**Comment by xee5ch** [comment]
Per @emkap01 there is a sample XLS file that seems to be a cleaned version of similar data that can be found.  Just leaving this for future reference or analysis.

https://docs.google.com/spreadsheets/d/1zRGbvcg2X6RrwLuDdTq9SmCXQo-Mp_GOO-9kuxYc60Y/edit#gid=0

**Comment by xee5ch** [comment]
Minor progress and early in the process.

- Tested building a Docker container with normal CPython 3 and pdfquery (because I cannot get it working with Anaconda since it is not the default channel and is a per user build)
- Emailed DC OpenData address like Neal in other tickets asking if the only way to get access to this is through PDF.

@NealHumphrey: TOPA data is marked as high and PDF of Excel looks like the only source, how bad do we want routine manual massaging of the data to get it in?

**Comment by NealHumphrey** [comment]
@xee5ch CNHED maintains (maintained?) a Google Spreadsheet where they manually pulled out some of this information - which could be a source for historical data, at least. I'm not sure how up to date it is. Besides that, I think that getting this in machine-readable format (probably an XLS spreadsheet) is possible but will require pressure to DHCD. The best method to do that is
a) Contact opendata, the open data office (Traci Hughes), and DHCD to start the process of pushing for it in machine readable format instead of just pdf
b) Go ahead and set up some PDF reading to require manual intervention, plan to update our data maybe once a month or so, show our tool to DHCD and use that to say hey, it actually is important. 

If we don't get DHCD cooperation on it, we can decide whether to keep doing any manual processing of PDFs, but for now it's better to get it in even if we're not sure we can maintain it. 

I'm copying you on an email to Scott at CNHED to see if he knows more.

**Comment by xee5ch** [comment]
OK seems we are on the same page given your reply. Also for others, Neal sent a follow up email to CNHED contacts about the provenance of their Google spreadsheet data.

I will toy with PDF manipulation this weekend.

**Comment by NealHumphrey** [comment]
@xee5ch So I got an update on this from Urban/DHCD. 

1) Peter has spreadsheet version(s) of the data from the DHCD website that we can get regularly, as DHCD emails the spreadsheet version to housing advocates. Later we can figure out how to tap into that data source or have Urban manually upload them regularly. 

2) We can get older data from CNHED's google spreadsheet. It should be about as accurate as older source data from DHCD. 

I'll get you set up with both data sources if you want to take this one on

**Comment by NealHumphrey** [comment]
@xee5ch If you sync your data folder (run this from the root of the repo: `aws s3 sync s3://housinginsights data --profile housinginsights`) you'll have 4 new files in the /raw/TOPA_notices folder - 3 years of topa notices (files starting with Rcasd_) and a data dictionary with the field definitions for those files. Have at it!

You should follow the standard 'add a new data source' instructions as we talked about - hopefully straightforward! The one thing you should talk to @jkwening about is that since these TOPA notices can sometimes coincide with our project table records, we'll want to add a step to the data cleaning that checks the project table for any matching records. He's been doing some work on how to do that for the DCHousingApiConn work, so those methods should be put up into the base class so both cleaners can use them.

**Comment by xee5ch** [comment]
Excellent. I will look tonight or tomorrow.

**Comment by xee5ch** [comment]
An update from the end of the hackathon. I have uploaded the data and have discussed the high priority columns with Eric.  Will keep working on this, per @NealHumphrey and have a PR soon for adding 2015, 2016, and 2017 data in a separate `topa` table once I have more than rudimentary cleaners.

**Comment by xee5ch** [comment]
Sorry, an overdue update.  I had issues determining where I went astray, but I was not setting recreate_table and was not capturing the different years like census and other aggregate tables.  Shame on me.  This is it, but needs more work.

https://github.com/xee5ch/housing-insights/tree/ingestion-topa-notices

It appears I have a dirty commit with my IDE auto-formatting sloppy whitespacing that is irrelevant and just aesthetic.  I guess the real question, @jkwening and @emkap01, is how to handle NHILCID because we have agreed changes are afoot.  This does next to no cleaning in Cleaners.py, but I expect you will want things done differently.  I will be sure to follow up out of band and tweak this as needed to make sure the data meets the needs of the group, rebase the commit, and send it along.

**Comment by NealHumphrey** [comment]
@xee5ch - John and I talked yesterday about some improvements to the recreate_table system that will better be able to handle updates from multiple files going into one table. For now, just make sure the replace_table field in meta.json is `false` and then rebuild the database any time you test re-adding the data, so you don't end up with duplicates. This will be improved soon. 

If you make a PR I can review whenever you're ready! Feel free to make it as WIP if it's not ready yet but just want feedback on code.

**Comment by xee5ch** [comment]
OK I'll just commit this afternoon or evening. I have not done much validation as data seems where it needs to be.  The NHILC ID issue I am not sure how were resolving it yet.

I also diffed other data sources quickly and had the aha moment re the reloaddata JSON param the evening after the hackathon. Duh.

Anyway I'll give it to you and await your orders.

**Comment by NealHumphrey** [comment]
Cool. We'll figure out the nlihc_id as part of the work @jkwening is doing on identifying duplicate projects via address.
