### ISSUE TITLE
hotfix - Issue in mar.py after refactor

### ISSUE THREAD

**Issue by jkwening** [codefordc/housing-insights#262]
Still referencing `self.conn.get()` after refactoring to inherit from BaseApiConn...fixed by replacing reference with `self.get()`.

**Comment by NealHumphrey** [comment]
@jkwening I ran into this yesterday too; hotfix should already be in dev as of ~5pm yesterday.

**Comment by jkwening** [comment]
@NealHumphrey great - thanks! I'll cancel my pull request. I added an additional method for reverse lookup given lat and long and test case for mar.py - I'll just ship it along with what I'm doing with dchousing insertion code when ready unless someone needs it sooner.

Also, if @ehenry2172 can't complete #175 I can take that one one also and push include my work in that for completeness instead.

**Comment by NealHumphrey** [comment]
No need to cancel your PR - I can go ahead and merge your other improvements in now. It's always better to merge in quickly in this kind of project since with so many people it's much more likely that multiple people will touch the same code. Merge fast, pull often - dev might break, but that's what master is for.
