### ISSUE TITLE
filter.js filters out non-matching null values. should it ignore instead?

### ISSUE THREAD

**Issue by ostermanj** [codefordc/housing-insights#311]
Applying the filters in the left sidebar filters out projects/buildings with null values in the properties being filtered. Nulls should perhaps be ignored instead (?)

For example, 34 of the 360 projects have `null` project unit counts. Activating *any* of the filters will filter those projects out. From there, there's no way to get back to having all 360 show.

Making separate issue so it's not lost in #273

**Comment by NealHumphrey** [comment]
So a quick summary of why this behaves as it does:

- The filtering code uses a for loop to go through all of the `filterValues.whatever` elements of the State module. If no filters have been selected yet, there are none to iterate over and no filtering is applied. 
- When the user drags a slider, the selected min and max (based on the slider min/max) are added to the State module.
- If the user then drags the min slider back to its lowest position, the `filterValues.proj_units_tot` element remains with whatever the min is, so Nulls are always excluded. Currently the min/max are hard coded, but we will be adding these to the API so that the *real* min and max are shown. 

Ways to fix this:
1) Set the min value of all sliders to zero, and add logic that interprets a min of zero and a Null data value as the same

or

2) Add a 'clear filter' button (which we'll already be adding to the pillboxes) that instead of setting filter criteria to their min and max values actually removes the filter from the State Module. 

We could also implement both for the most flexibility / clarity.

**Comment by NealHumphrey** [comment]
Note: we want to fix this by adding a checkbox for 'include nulls' in the slider filter box. Should re-write up this ticket to describe this functionality.

**Comment by ptgott** [comment]
@NealHumphrey Is this issue closeable?

**Comment by NealHumphrey** [comment]
yep!
