### ISSUE TITLE
Lat/Lon incorrect from MAR, and Street view not correctly calculated

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#379]
In the 'add_mar_id' method of the cleaner for projects, we manually create a google street view if it is not available in the MAR. However, this is not done completely accurately. There are two issues:
- We use the project's lat/lon instead of the street view car lat/lon. Google moves this to the closest street view available, which might be on an adjacent street
- The heading is set to default to 180 degrees; instead, we need to calculate the bearing between the street view car and the building itself. 

In an example, this revealed a bigger issue:
- More disturbingly, it looks like the Lat/Lon from the MAR might not actually be correct. 

Here's an example:
- Searching Google for the address  1710 7th St NW yields [this street view](https://www.google.com/maps/place/1710+7th+St+NW,+Washington,+DC+20001/@38.9130085,-77.0219406,3a,82.3y,1.84h,90.51t/data=!3m6!1e1!3m4!1s*211m2*211y9923602546009974685*212y6707206558547221454*212m2*211x389129693*212x3524748059*213m2*211y9923602121828923723*212y8358534528308367527*215m2*211x389129693*212x3524748059!2e0!7i13312!8i6656!4m5!3m4!1s0x89b7b7f02716279d:0x5d14c8d425609bce!8m2!3d38.9129693!4d-77.0219237)
- This is the street view [generated by our code](https://www.google.com/maps/@38.9126384,-77.0216128,3a,75y,182.25h,93.35t/data=!3m6!1e1!3m4!1saEPcgJPYyWDiR4_v0K9NPw!2e0!7i13312!8i6656)
- This is the lat/lon from the mar for that building [shown on Google Maps](https://www.google.com/maps/place/38%C2%B054'45.5%22N+77%C2%B001'17.8%22W/@38.91289,-77.0218596,18.94z/data=!4m5!3m4!1s0x0:0x0!8m2!3d38.9126384!4d-77.0216128)

With this one the biggest issue is that  lat/lon is not correct, meaning that not only street view is wrong but also the dot will be put in the wrong place on the map for this. 

Maybe there is a correlation between when street view is not available and when lat/lon is incorrect?
Maybe the reverse geocode should also compare to Google's geocoding service and see if the two agree?

**Comment by NealHumphrey** [comment]
Notes on the angle between street view car and the building:
I researched a little bit and couldn't find the right solution quickly, but I did find this SO question that shows how to point the POV from truck to building using the computeHeading() method of the maps/streetview API, if you're using their javascript library instead of python: https://stackoverflow.com/questions/3198415/using-google-street-view-with-a-marker-how-do-i-point-the-pov-at-a-marker

**Comment by jkwening** [comment]
@NealHumphrey I did some further playing around and it looks like the reason why mar api calls is returning no street view url is because one actually doesn't exist. I need to verify some additional examples to confirm but that is definitely the case for 1710 7th ST NW. The address points you to the street view for 1712 7th ST NW instead. In playing with street view, moving along the street goes from 1708 to 1712; 1710 doesn't exist.

After doing some additional research I found this info on endpoint access that returns the closest available street view location within a given distance (50 meters is default): [https://andresmartinezsoto.wordpress.com/2012/05/19/php-some-google-maps-v3-streetview-tricks/](https://andresmartinezsoto.wordpress.com/2012/05/19/php-some-google-maps-v3-streetview-tricks/)
I think this is the approach we should use - it mimics what happens if you enter the address into google maps.
